name: flutter_angle_platform_interface
description: "Flutters Almost Native Graphics Layer Engine is made by google to use OpenGL ES API calls to one of the hardware-supported APIs available for that platform."
version: 0.0.1
homepage: https://github.com/Knightro63/flutter_angle/tree/main/flutter_angle_platform_interface

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
