name: flutter_angle
description: "Flutters Almost Native Graphics Layer Engine is made by google to use OpenGL ES API calls to one of the hardware-supported APIs available for that platform."
version: 0.0.5
homepage: https://github.com/Knightro63/flutter_angle/tree/main/flutter_angle

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.20.0"

topics:
  - opengl
  - angle
  - glsl

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.3.0
  dylib: ^0.3.3
  ffi: ^2.1.2
  flutter_angle_darwin: ^0.0.2
  #flutter_angle_windows: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^12.0.0
  lint: ^2.3.0
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        package: org.fluttergl.flutter_angle
        pluginClass: FlutterAnglePlugin
      windows:
        pluginClass: FlutterAnglePlugin
        #default_package: flutter_angle_windows
      ios:
        default_package: flutter_angle_darwin
      macos:
        default_package: flutter_angle_darwin
      web:
        default_package: flutter_angle_web
