name: flutter_angle_web
description: "Flutters Almost Native Graphics Layer Engine is made by google to use OpenGL ES API calls to one of the hardware-supported APIs available for that platform."
version: 0.0.1
homepage: https://github.com/Knightro63/flutter_angle/tree/main/flutter_angle

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.20.0"

topics:
  - opengl
  - angle
  - glsl

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.3.0
  dylib: ^0.3.3
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  plugin_platform_interface: ^2.1.8
