name: flutter_angle_native_array
description: "A type cast array simular to js."
version: 0.0.1
homepage: https://github.com/Knightro63/flutter_angle/tree/main/flutter_angle

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^12.0.0
  lint: ^2.3.0
  plugin_platform_interface: ^2.1.8